site_name: OVERVOLT
site_url: https://tembee2.github.io/OVERVOLT
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - toc.integrate
    - content.code.annotate
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
  logo: assets/Gear.png
  favicon: assets/Gear23.png
nav:
  - Home: index.md
  - Materials: Categories/Materials.md
  - Buildings: Categories/Buildings.md
  - Talents: Categories/Talents.md
  - Blueprints: Categories/Blueprints.md
plugins:
  - glightbox