site_name: OVERVOLT
site_url: https://tembee2.github.io/OVERVOLT
site_description: The official wiki for OVERVOLT, a Roblox roguelike factoru building game! The wiki contains pages about the ores, buildings, alloys and a basic tutorial.
site_author: Tembee2

repo_name: tembee2/OVERVOLT
repo_url: https://github.com/tembee2/OVERVOLT
edit_uri: ""

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - toc.integrate
    - content.code.annotate
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
  logo: assets/Gear.png
  favicon: assets/Gear23.png
nav:
  - Home: index.md
  - Starting out: starting-out.md
  - Materials: Categories/Materials.md
  - Buildings: Categories/Buildings.md
  - Talents: Categories/Talents.md
  - Blueprints: Categories/Blueprints.md
plugins:
  - glightbox